
import { Prompt, Category } from "../context/PromptContext";

// Mock categories
export const mockCategories: Category[] = [
  { id: "cat-1", name: "Copywriting", color: "#3B82F6" },
  { id: "cat-2", name: "Creative Writing", color: "#10B981" },
  { id: "cat-3", name: "Code", color: "#F59E0B" },
  { id: "cat-4", name: "Academic", color: "#8B5CF6" },
  { id: "cat-5", name: "Business", color: "#EC4899" },
  { id: "cat-6", name: "Personal", color: "#6366F1" },
];

// Mock prompts
export const mockPrompts: Prompt[] = [
  {
    id: "prompt-1",
    title: "Blog Post Introduction Generator",
    content: "I want you to write an engaging introduction for a blog post about {topic}. Make it approximately 100 words, hook the reader with an interesting fact or question, and hint at what valuable information the post will contain.",
    category: "cat-1",
    createdAt: "2023-08-15T10:30:00Z",
    updatedAt: "2023-08-15T10:30:00Z",
    createdBy: {
      id: "user-1",
      name: "Demo User",
      avatar: "/placeholder.svg",
    },
    likes: 42,
    liked: false,
    saved: true,
  },
  {
    id: "prompt-2",
    title: "Short Story Generator",
    content: "Write a {genre} short story set in {setting} featuring a character who is {character trait}. The story should have an unexpected twist at the end. Keep it under 500 words.",
    category: "cat-2",
    createdAt: "2023-09-02T14:20:00Z",
    updatedAt: "2023-09-02T14:20:00Z",
    createdBy: {
      id: "user-2",
      name: "Creative Writer",
      avatar: "/placeholder.svg",
    },
    likes: 78,
    liked: true,
    saved: false,
  },
  {
    id: "prompt-3",
    title: "React Component Generator",
    content: "Generate a React functional component for {component type} with TypeScript. Include proper types, state management with React hooks, and comments explaining the code. Make it follow best practices and be accessible.",
    category: "cat-3",
    createdAt: "2023-07-22T09:15:00Z",
    updatedAt: "2023-07-22T09:15:00Z",
    createdBy: {
      id: "user-3",
      name: "Tech Coder",
      avatar: "/placeholder.svg",
    },
    likes: 135,
    liked: false,
    saved: true,
  },
  {
    id: "prompt-4",
    title: "Email Response Template",
    content: "Draft a professional email response to {situation}. The tone should be {tone} and the length should be {length}. Include appropriate greetings and sign-offs.",
    category: "cat-5",
    createdAt: "2023-10-05T11:45:00Z",
    updatedAt: "2023-10-05T11:45:00Z",
    createdBy: {
      id: "user-1",
      name: "Demo User",
      avatar: "/placeholder.svg",
    },
    likes: 29,
    liked: false,
    saved: false,
  },
  {
    id: "prompt-5",
    title: "Research Paper Outline",
    content: "Create a detailed outline for a research paper on {topic}. Include introduction, literature review, methodology, discussion, and conclusion sections. For each section, provide bullet points of what should be covered.",
    category: "cat-4",
    createdAt: "2023-09-18T16:30:00Z",
    updatedAt: "2023-09-18T16:30:00Z",
    createdBy: {
      id: "user-4",
      name: "Academic Scholar",
      avatar: "/placeholder.svg",
    },
    likes: 47,
    liked: true,
    saved: true,
  },
  {
    id: "prompt-6",
    title: "Product Description Template",
    content: "Write a compelling product description for a {product type} that targets {target audience}. Highlight its {number} key features, benefits, and include a strong call-to-action. Keep it under 200 words and make it persuasive.",
    category: "cat-1",
    createdAt: "2023-08-30T13:10:00Z",
    updatedAt: "2023-08-30T13:10:00Z",
    createdBy: {
      id: "user-5",
      name: "Marketing Pro",
      avatar: "/placeholder.svg",
    },
    likes: 86,
    liked: false,
    saved: false,
  },
  {
    id: "prompt-7",
    title: "Daily Reflection Journal",
    content: "Create a journal entry template for daily reflection that asks about: 1) Three things I'm grateful for today, 2) One challenge I faced and how I addressed it, 3) Something I learned today, 4) How I took care of myself, and 5) One goal for tomorrow.",
    category: "cat-6",
    createdAt: "2023-10-10T19:40:00Z",
    updatedAt: "2023-10-10T19:40:00Z",
    createdBy: {
      id: "user-1",
      name: "Demo User",
      avatar: "/placeholder.svg",
    },
    likes: 125,
    liked: true,
    saved: true,
  },
  {
    id: "prompt-8",
    title: "Social Media Caption Generator",
    content: "Generate an engaging social media caption for {platform} about {topic}. The caption should be {tone} and include relevant hashtags. Keep it within the character limit for {platform}.",
    category: "cat-1",
    createdAt: "2023-09-25T15:20:00Z",
    updatedAt: "2023-09-25T15:20:00Z",
    createdBy: {
      id: "user-6",
      name: "Social Media Expert",
      avatar: "/placeholder.svg",
    },
    likes: 93,
    liked: false,
    saved: true,
  }
];
